In [4]:
import numpy as np

In [7]:
X=np.array([[1,0],[0,1]])
Y=np.array([[2,2],[2,2]])
Z=np.dot(X,Y)
Z

array([[2, 2],
       [2, 2]])

In [10]:
X=np.array([[1,0],[0,1]])
Y=np.array([[0,1],[1,0]])
Z=X+Y
Z

array([[1, 1],
       [1, 1]])

In [12]:
a=np.array([-1,1])
b=np.array([1,1])
np.dot(a,b) 

0

In [32]:
var = "01234567"
print(var[::2])

0246


In [16]:
int(3.99)

3

In [18]:
def add(x): 
    return(x+x)
add('1') 

'11'

In [21]:

A=['1','2','3'] 
for a in A: 
    print(2*a) 

11
22
33


In [23]:

for i in range(1,5): 
    if (i==2): 
        print(i)

2


In [29]:
class Rectangle(object): 
    def __init__(self,width=2,height =3,color='r'): 
        self.height=height 
        self.width=width 
        self.color=color 
        def drawRectangle(self): 
            import matplotlib.pyplot as plt 
            plt.gca().add_patch(plt.Rectangle((0, 0),self.width, self.height ,fc=self.color)) 
            plt.axis('scaled') 
            plt.show() 

In [30]:
a=np.array([0,1,0,1,0]) 
b=np.array([1,0,1,0,1]) 
a/b 

/home/jupyterlab/conda/envs/python/lib/python3.7/site-packages/ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


array([ 0., inf,  0., inf,  0.])